<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_profile_View</name>
   <tag></tag>
   <elementGuidId>e8a3230e-0ccc-42a8-b38a-c2a476e8b134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[2]/div[1]/div[2]/span[4]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[2]/div[1]/div[2]/span[4]/div/div/div/a</value>
   </webElementProperties>
</WebElementEntity>
