<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Settings</name>
   <tag></tag>
   <elementGuidId>29e6c673-1e61-47b6-9507-cd88e305d5b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[1]/div[2]/div/div/div[2]/nav/a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[1]/div[2]/div/div/div[2]/nav/a[6]</value>
   </webElementProperties>
</WebElementEntity>
