<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_users_options</name>
   <tag></tag>
   <elementGuidId>94d3caa6-fb6d-49ba-b36a-f1be05b068bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[2]/div[1]/div[2]/span[3]/div/div/div/div/div[2]/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[2]/div[1]/div[2]/span[3]/div/div/div/div/div[2]/ul</value>
   </webElementProperties>
</WebElementEntity>
