<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Share_Profile_span</name>
   <tag></tag>
   <elementGuidId>41c5fe9f-07c5-4e95-bda8-712c89a07a67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div[2]/div[1]/div[2]/span[4]/div/div/div/a/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '#' and (contains(text(), 'Shared Profile') or contains(., 'Shared Profile'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div[2]/div[1]/div[2]/span[4]/div/div/div/a/span</value>
   </webElementProperties>
</WebElementEntity>
